# YAML file to auto generate and update README files

name: auto-generate-readme
on:
  workflow_dispatch:
  # Above allows manual running of GitHub action through interface
  schedule:
    # auto generate each Monday at 8 AM
    - cron: '0 8 * * 1'

  push:
      branches: [ master ]
      # Anytime this YAML file gets updated rerun the jobs, comment out if only want to run at 8am on Mondays (above "on:"")

jobs:
  make-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repos
        uses: actions/checkout@v3
        with:
          repository: ahart1/TestRepo
          path: TestRepo
          token: ${{secrets.AUTOREADME_PAT}}
          # Above needed if private repo (need to provide credentials to add)

      

      - name: Checkout current version of repo
        uses: actions/checkout@v3
        with:
          path: main
          token: ${{secrets.AUTOREADME_PAT}}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release

      - name: Install and cache dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          working-directory: main

      - name: update_README
        run: |
          library("tidyverse")
          source("main/R/autoREADME.R")
          source("main/makeREADMEScript.R")
        shell: Rscript {0}

      - name: Commit files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: A. Hart
          message: "Auto update/generate README file."
          cwd: TestRepo
          push: true
          github_token: ${{secrets.AUTOREADME_PAT}}
       # Will need to periodically update personal access token (limited lifespan) & corresponding secrets

      

